export const NOTIFICATION_TYPE = {
  PROJECT_MEMBER_ADDED: "PROJECT_MEMBER_ADDED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_COMMENTED: "TASK_COMMENTED",
};
